services:
  backend:
    build: ./backend
    container_name: novablog-backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: novablog-frontend-builder
    command: ["true"]
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: novablog-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
